[package]
name = "todo_server_axum"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
argon2 = "0.6.0"
axum = "0.8.9"
chrono = { version = "0.4.45", features = ["serde"] }
config = "0.15.26"
insta = { version = "1.48.0", features = ["json", "redactions", "serde"] }
jsonwebtoken = { version = "11.1.0", features = ["rust_crypto"] }
rand = "0.10.3"
regex = "1.13.1"
reqwest = { version = "0.13.5", features = ["json"] }
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sqlx = { version = "0.9.0", features = ["chrono", "runtime-tokio", "sqlite"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "parking_lot", "rt-multi-thread"] }
tower = "0.5.3"
tower-http = { version = "0.7.1", features = ["compression-full", "cors", "decompression-full", "timeout", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
utoipa = { version = "5", features = ["axum_extras"] }
utoipa-axum = "0.3.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "reqwest"] }
uuid = { version = "1.26.1", features = ["v7"] }

[dev-dependencies]
serde_json = "1.0.151"
