// Mocks generated by Mockito from annotations
// in file_organizer/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:file_organizer/src/models/file_info.dart' as _i4;
import 'package:file_organizer/src/services/file_info.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i2.FileService {
  MockFileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.FileInfo>> collectFiles(
    _i5.Directory? dir, {
    bool? recursive = false,
    Set<String>? extensions,
  }) => (super.noSuchMethod(
    Invocation.method(
      #collectFiles,
      [dir],
      {#recursive: recursive, #extensions: extensions},
    ),
    returnValue: _i3.Future<List<_i4.FileInfo>>.value(<_i4.FileInfo>[]),
  ) as _i3.Future<List<_i4.FileInfo>>);

  @override
  _i3.Future<String> moveFile(_i5.File? source, String? destDir) =>
      (super.noSuchMethod(
        Invocation.method(#moveFile, [source, destDir]),
        returnValue: _i3.Future<String>.value(
          _i6.dummyValue<String>(
            this,
            Invocation.method(#moveFile, [source, destDir]),
          ),
        ),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> readAsString(_i5.File? file) => (super.noSuchMethod(
    Invocation.method(#readAsString, [file]),
    returnValue: _i3.Future<String>.value(
      _i6.dummyValue<String>(this, Invocation.method(#readAsString, [file])),
    ),
  ) as _i3.Future<String>);

  @override
  _i3.Future<void> writeAsString(_i5.File? file, String? content) =>
      (super.noSuchMethod(
        Invocation.method(#writeAsString, [file, content]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
